language: java

services:
  - docker

script:
  - mvn clean install
  - docker build -t kambroziak/microader:latest .
 
deploy:
  provider: script
  script: bash docker_push $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    branch: master
