language: java

services:
  - docker

script:
  - mvn clean install
  - docker build -t kambroziak/microadder:latest .
 
deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push.sh $DOCKER_USERNAME $DOCKER_PASSWORD
  on:
    branch: master
